### ISSUE TITLE
Use subcommands for example/cli

### ISSUE THREAD

**Issue by stevvooe** [docker/infrakit#188]
It is very odd to have `infrakit/foo` everywhere. No need to have all the different packages. Just use cobra subcommands.

**Comment by wfarner** [comment]
It does appear overly-complicated at first glance, but the separate commands are an artifact of the plugin-oriented nature of InfraKit.  Since plugins are daemons that communicate via sockets, they are built and executed independently.  Without language-level support for dynamic library loading, i'm not sure there's a better way.  Any ideas?

**Comment by stevvooe** [comment]
@wfarner You could use git-style sub-command resolution.

**Comment by wfarner** [comment]
@stevvooe not a good fit here, since plugins will be coming from different build sources, and can't be expected to be placed in the same directory.

**Comment by stevvooe** [comment]
@wfarner Git doesn't require this. It just does a search through a path variable. They don't need to be in the same directory. [`exec.LookPath`](https://golang.org/src/os/exec/lp_unix.go?s=931:973#L24) actually searches all paths. So, if you're using two projects, you just do `PATH=$PROJ_ONE_PATH:$PROJ_TWO_PATH`.

**Comment by wfarner** [comment]
Capturing offline discussion with @stevvooe, a CLI-oriented flow won't work well across plugin boundaries as it would require CLI-specific APIs for plugin communication (e.g. surfacing help text, arguments, output, etc).  The long-term goal is to delegate plugin management to the environment InfraKit is used in.  For example, in Docker Engine we will provide scaffolding to run them as Docker plugins.
