### ISSUE TITLE
Lifecycle management for dependent resources in terraform plugin

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#561]
Today, multiple resources can be defined in a single instance definition (for example, a VM resource and a volume resource).  These 2 resources will be included in a single `.tf.json` file and terraform handles the provision ordering.

This approach helps on the initial provision since these dependent resources are coupled together. However, when performing a rolling update, Infrakit will remove the single `.tf.json` file and then create a new one — this causes BOTH the VM and the associated volume to be destroyed and then replaced.

We need a mechanism to decouple the volume so that, during a rolling update, the volume will remain and only the VM will be destroyed and replaced.

**Comment by chungers** [comment]
I think at a minimum, we want to be able to have resources written in different `.tf.json` files so that their lifecycle can be independently managed.  For example, when the instance is to be terminated, we can simply remove its corresponding `tf.json` file without destroying, say, a volume that was provisioned with it but is intended to survive across instance terminations.

In the terraform plugin, we have a map of resource types and resource objects and currently everything is written as a single file named by the instance id -- https://github.com/docker/infrakit/blob/master/examples/instance/terraform/plugin.go#L485

Here the instance id originally had the connotation of a compute instance, but in the most general sense, the id is just a per-invocation identifier of the plugin.  So if the plugin has a template of N resources that are all related to each other, a single file of `infrakit-xxxxx.tf.json` would contain N resources.   

So this is my suggestion:  
  1. let's come up with a way to support grouping of resources in separate files....  for example, I should be able to say something like:
```
    {   
         "fileprefix1" : [ "softlayer_virtual_guest", "softlayer_ssh_key" ],
         "fileprefix2" : [ "softlayer_volume" ]
     }
```
   This basically says, "put the resource types `softlayer_virtual_guest` and `softlayer_ssh_key` in a file named `fileprefix1-<instance_id>.tf.json`, while resource of the type `softlayer_volume` is written to a separate file `fileprefix2-<instance_id>.tf.json`.  

  To do this I think we can add a field here (say, `Related` or something) 
 https://github.com/docker/infrakit/blob/master/examples/instance/terraform/plugin.go#L145

  2. Change the code here https://github.com/docker/infrakit/blob/master/examples/instance/terraform/plugin.go#L462 to write out multiple files based on the rule above.

  3. Change the way `DescribeInstances` and `Destroy` work...  Since now we have multiple files, and not all files are to be searched during describe and removed during destroy, we'd need a way to associate the methods `describe` and `destroy` to the file prefixes.   Maybe we can add another field like above, but for associating verbs to file prefixes.

**Comment by kaufers** [comment]
Thanks for the response @chungers. Can we get a concrete example of the new schema for the `Properties` of `instance-terraform`. For example, let’s use https://github.com/docker/infrakit/blob/master/examples/instance/terraform/plugin_test.go#L54-L93. This definition is basically:

```
{
	"resource" : {
		"softlayer_file_storage": {
			"worker_file_storage": {…}
		},
		"softlayer_block_storage": {
			"worker_block_storage": {…}
		},
		"softlayer_virtual_guest" : {	
			"host": {…}
		}
	}
}
```

And this creates a single file like
```
# instance-12345.tf.json
{
    "resource": {
      "softlayer_block_storage": {
        "instance-12345-worker_block_storage": {…}
      },
      "softlayer_file_storage": {
        "instance-12345-worker_file_storage": {…}
      },
      "softlayer_virtual_guest": {
        “instance-12345”: {…}
      }
    }
}
```

Should the updated definition be:
```
{
	“<file-prefix1>”: [“softlayer_virtual_guest”],
	“<file-prefix2>”: [“softlayer_file_storage”, “softlayer_block_storage”],
	"resource" : {
		"softlayer_file_storage": {
			"worker_file_storage": {…}
		},
		"softlayer_block_storage": {
			"worker_block_storage": {…}
		},
		"softlayer_virtual_guest" : {	
			"host": {…}
		}
	}
}
```
This would then create 2 files:
```
# <file-prefix1>-instance-12345.tf.json
{
    "resource": {
      "softlayer_virtual_guest": {
        “instance-12345”: {…}
      }
    }
}
# <file-prefix2>-instance-12345.tf.json
{
    "resource": {
      "softlayer_block_storage": {
        "instance-12345-worker_block_storage": {…}
      }
      "softlayer_file_storage": {
        "instance-12345-worker_file_storage": {…}
      }
    }
}
```

Is this what you are thinking?

Also, do you think that we need a top-level JSON key to identify the file groupings in the instance `Properties` (ie, a `groupings` key that is peer to `resource`)? This would then look like:
```
{
	“groupings”: {
		“<file-prefix1>”: [“softlayer_virtual_guest”],		
		“<file-prefix2>”: [“softlayer_file_storage”, “softlayer_block_storage”]
	},
	"resource" : {
		"softlayer_file_storage": {
			"worker_file_storage": {…}
		},
		"softlayer_block_storage": {
			"worker_block_storage": {…}
		},
		"softlayer_virtual_guest" : {	
			"host": {…}
		}
	}
}
```

**Comment by chungers** [comment]
@kaufers 

> Also, do you think that we need a top-level JSON key to identify the file groupings in the instance Properties (ie, a groupings key that is peer to resource)? This would then look like:
```
{
	“groupings”: {
		“<file-prefix1>”: [“softlayer_virtual_guest”],		
		“<file-prefix2>”: [“softlayer_file_storage”, “softlayer_block_storage”]
	},
	"resource" : {
		"softlayer_file_storage": {
			"worker_file_storage": {…}
		},
		"softlayer_block_storage": {
			"worker_block_storage": {…}
		},
		"softlayer_virtual_guest" : {	
			"host": {…}
		}
	}
}
```
That's exactly what I was talking about.  Thank you.

We also need to have a way to specify *which* file to look for in the case of DescribeInstances and Destroy.   In the code there's a function to look for VMs like [here](https://github.com/docker/infrakit/blob/master/examples/instance/terraform/plugin.go#L179).   This code can now be made generic if we know *which file* to look for and for what *resource type* we should be used for listing and destroy.   Essentially with this support the terraform plugin can be an instance plugin of anything terraform can provision, not just for compute -- plus it can manage related resources that may have separate lifecycle.

As a aside, currently `DescribeInstances` doesn't take into account of other resource objects -- it just lists VM instances.  It'd be nice to get a list of everything...  maybe we can do that as `Properties` in the `instance.Description`.

**Comment by kaufers** [comment]
@chungers Yes, this makes sense. How about something like this:

```
{
  "lifecycle": [
    ["softlayer_virtual_guest"],    
    ["softlayer_file_storage", "softlayer_block_storage"]
  ],
  "actions" : {
    "describe" : ["softlayer_virtual_guest", "softlayer_file_storage", "softlayer_block_storage"],
    "destroy" : ["softlayer_virtual_guest"]
  },
  "resource" : {
    "softlayer_file_storage": {
      "worker_file_storage": {...}
    },
    "softlayer_block_storage": {
      "worker_block_storage": {...}
    },
    "softlayer_virtual_guest": {  
      "host": {...}
    }
  }
}
```

* `lifecycle` defines the groups of resources that map to individual JSON files; IMO the user shouldn't care about how we name the files so the value is just a list of resource type lists.
* `actions` defines the behavior (as you stated) and it seems that we only need resource types here; can you think of anything else we'd need? We should be able to parse all files and pull the matching resource types.

IMO this is more refined but it does put the onus on the plugin to determine a naming convention and then we need to parse all files for the chosen `action`.

One issue that I can think of related to #562. Depending on how that one gets solved, I can envision defining **both** the shared and dedicated volume in the `managers` definition. If so, we'd want to be able to destroy a _specific_ `softlayer_file_storage` resource (ie, the dedicated one) while leaving the shared one; in this case only defining the resource type in the `actions` is too coarse.

Thoughts?

**Comment by chungers** [comment]
@kaufers I like your proposal; I think it's much more refined than the example I gave.

I agree, however, that this design may need a bit of tweak to support #562.  In essence, a instance of a given resource type (e.g. `softlayer_block_storage`) can have different purposes: dedicated to a compute instance or shared.  So the actions that be taken against the instance are different -- destroy along with the compute instance in the former and preserve in the latter case.   

I think instead of introducing new top level fields like `lifecycle` or `grouping` how about we just add a couple of fields to the resource struct to annotate what can be done for each resource?  Then the terraform plugin can look at the flags for each resource and group them into different files and operate on them accordingly (list and/or destroy)?   We can always remove these extra fields before feeding that to terraform so it won't complain.  If the extra fields are not provided, then every resource type instances get lumped into the same file.

So for example, previously we have
```json
{
  "resource" : {
    "softlayer_file_storage": {
      "worker_file_storage": {...}
    },
    "softlayer_block_storage": {
      "worker_block_storage": {...}
    },
    "softlayer_virtual_guest": {  
      "host": {...}
    }
}
```
Now it becomes
```json
{
  "resource" : {
    "softlayer_file_storage": {
      "worker_file_storage": {...},
      "persistent" : false,   # <---- new extra field, if not set, defaults to false per golang zero value.
      "main" : false,  # this resource's id is not used as instance.ID when describing resources.
    },
    "softlayer_file_storage": {
      "shared_manager_storage": {...},   # <-- here we have a same resource type but now shared
      "persistent" : true,   # <---- write this resource to a separate file not touched during destroy
    },   # note here there's no `main` field.  Defaults to false
    "softlayer_block_storage": {
      "worker_block_storage": {...}   # no `persistent` nor `main`...  so write to same file that will be removed when destroying instances.
    },
    "softlayer_virtual_guest": {  
      "host": {...},
      "persistent" : false,   # <---- this is the extra field
      "main" : true  # <-- means we'd search for this resource type and use its id for describe instances 
    }
}
```
So we can get away with just two new booleans... `persistent` and `main`.  `Persistent` controls the behavior of destroy -- so we'd only need two files since it's a binary value -- let's just name them `infrakit-<generated_id>.tf.json` and `infrakit-persistent-<generated_id>.tf.json`. 

When we describe instances, we open two files for each "instance" -- its destroyable and persistent versions.  We gather the resource objects and depending on which resource has the `main` set to true, we use that instance's ID as the instance id when returning the results of `DescribeInstances`. 

When we destroy, we remote the non-persistent file for every instance.  

As for this mapping of what resource is main/persistent, we can store that in memory, since that information can be reconstituted every time a `Validate` is called and we only need to cache that mapping information for describe and destroy calls which get nothing or only the id's as input.

Thoughts?

**Comment by kaufers** [comment]
@chungers I like this new approach but I think that there is one more use case that we might want to consider: using dedicated volumes for workers. In this flow, we'd create a dedicated volume for _worker-x_ and, if that worker died, the replacement worker would be associated with the _existing_ volume (that was being used by _worker-x_). A few questions/comments on this use case:

1. Do you think that this is even valid?
2. We'd have think about how we name the instances so that we can correlate a worker to a specific volume (and ensure that rolling updates wire things up correctly). Maybe we change the naming convention from `instance-<ts>.tf.json` to something like `instance-n.tf.json` (where `n` is just a count that is incremented/decremented on scale up/down); by using `n` we'd simply have `volume_n` that would always map to `instance-n` (even when `instance-n` has a rolling update applied).

If this is valid, then how about supporting 3 values for a new `@persistent` property:
- `global`: This resource is **completely** decoupled from the instance (like a shared volume) and would not be removed if the instance is removed.
- `dedicated`: This resource is **loosly** coupled to a specific instance (ie, `worker-n`) and would be destroyed on scale down (only if `worker-n` was being removed) but would not be destroyed on a rolling update.
- `default`: This resource is **tightly** coupled with the lifecycle of the resource and it is destroyed/recreated on a rolling update.

I'm also trying to understand the motivation for **not** included everything in `DescribeInstances`. Why wouldn't we want to include everything? Is it because a `global` resource may map to multiple resources?

Thanks!

**Comment by chungers** [comment]
@kaufers 

> 1. Do you think that this is even valid?

Yes.  This is actually a really good point.  Currently the group controller will naively destroy an instance in a rolling update without regard to anything that's associated to the instance.   More specifically, the _context_ is there (ie. this destroy for a rolling update) but that context isn't expressed in the SPI by the time the instance plugin is invoked.   

In the flavor plugin, there's the notion of a 'Drain', but it has a higher-level semantic than what to do with the infrastructure resources like keeping a volume around or destroy it along with the instance.  So doing these low-level resource type of things doesn't make sense inside a Flavor plugin.

So, your insight leads me to think that we should change the SPI to give more context to certain operations -- in particular `Destroy`.  Even `Provision` can use a context -- so that it knows to reattach resources for those that are, as you call it below, "dedicated", in context of an update.

> 2. We'd have think about how we name the instances so that we can correlate a worker to a specific volume (and ensure that rolling updates wire things up correctly). Maybe we change the naming convention from instance-<ts>.tf.json to something like instance-n.tf.json (where n is just a count that is incremented/decremented on scale up/down); by using n we'd simply have volume_n that would always map to instance-n (even when instance-n has a rolling update applied).
If this is valid, then how about supporting 3 values for a new @persistent property:
>
> + global: This resource is completely decoupled from the instance (like a shared volume) and would not be removed if the instance is removed.
> + dedicated: This resource is loosely coupled to a specific instance (ie, worker-n) and would be destroyed on scale down (only if worker-n was being removed) but would not be destroyed on a rolling update.
> + default: This resource is tightly coupled with the lifecycle of the resource and it is destroyed/recreated on a rolling update.
I'm also trying to understand the motivation for not included everything in DescribeInstances. Why wouldn't we want to include everything? Is it because a global resource may map to multiple instances?

I like these three "enums" that you have defined.  I think they capture a wide swath of use cases in a general way.  

While we can't support all these semantics properly until we make changes to the instance SPI, I think we can definitely start that with the Terraform plugin and implement using the approach you mentioned.   One thing we should look at is the handling of 'dedicated' resources because it may require creation / removal of some "attachment" type of object / structure that represent association of two resources in Terraform.  For example, on AWS there's a volume attachment object that needs to be created / destroyed.  So the handling of these pseudo resource objects need a bit of design and care.

**Comment by kaufers** [comment]
@chungers I started implementing the `.tf.json` file decomposition based on the `@persistence` property.

What do you think about scoping `global` resources to the group that they are associated with?  This way we (in theory) could destroy them when the group is removed (analogous to removing `dedicated` resources on scale down). This would mean that `global` resources could only be created from a `group` commit (is this an acceptable restriction?).

Here's a concrete example (with a few bogus resource types to show the groupings):
```
{
  "resource" : {
    "softlayer_virtual_guest": {  
      "host": {...}
    }
    "softlayer_file_storage": {
      "worker_fs": {
        "@persistence": "dedicated",
        ...
      }
    },
    "softlayer_block_storage": {
      "shared_block_storage": {
        "@persistence": "global",
        ...
      }
    },
    "another-dedicated-resource-type": {  
      "another-dedicated-name": {
        "@persistence": "dedicated",
        ...
      }
    },
    "another-default-resource-type": {  
      "another-default-name": {...}
    }
}
```

This created 3 files:
```
$ ls -l
total 24
-rw-r--r--  1 kaufer  staff  296 Jun  2 14:48 dedicated-1234.tf.json
-rw-r--r--  1 kaufer  staff  170 Jun  2 14:48 global-mygroup.tf.json
-rw-r--r--  1 kaufer  staff  330 Jun  2 14:48 instance-1234.tf.json
```

```
$ cat instance-1234.tf.json 
{
    "resource": {
      "another-default-resource-type": {
        "instance-1234-another-default-name": {...}
      },
      "softlayer_virtual_guest": {
        "instance-1234": {
          "tags": {
            "infrakit.group": "mygroup"  <-- NOTE required tag for @global resources
          },
          ...
        }
      }
    }
  }
```
```
$ cat dedicated-1234.tf.json 
{
    "resource": {
      "another-dedicated-resource-type": {
        "instance-1234-another-dedicated-name": {...}
      },
      "softlayer_file_storage": {
        "instance-1234-worker_fs": {...}
      }
    }
  }
```
```
$ cat global-mygroup.tf.json
{
    "resource": {
      "softlayer_block_storage": {
        "mygroup-shared_block_storage": {...} . <-- NOTE prefix is `infrakit.group` tag on main VM
      }
    }
  }
```

The file naming conventions are:
- `default` resources: `<id>.tf.json` -- `instance-1234.tf.json`
- `dedicated` resources: `dedicated-<id-ts>.tj.json` -- `dedicated-1234.tf.json`
- `global` resources: `global-<groupId>.tf.json` -- `global-mygroup.tf.json`

The resource naming conventions are:
- Main VM resource: `<id>` -- `instance-1234`
- Other `default` resources: `<id-ts>-<givenName>` -- `1234-another-default-name`
- `dedicated` resources: ^ same
- `global` resources: `<groupId>-<givenName>` -- `mygroup-block-storage`

**Comment by chungers** [comment]
> What do you think about scoping global resources to the group that they are associated with? This way we (in theory) could destroy them when the group is removed (analogous to removing dedicated resources on scale down). This would mean that global resources could only be created from a group commit (is this an acceptable restriction?).

I like the idea but with a slight twist...  how about we label the resources using the following convention:

if Instance B1 of type B is to be attached to instance A1 of A, we label A1 with `infrakit.attach` which has a list of resource names to attach.  In this case, `infrakit.attach=B1,name_of_something_else`  

Which file the resource should belong.... we can do with a field in the spec called `scope` instead of the `@persistence`.  The following values are possible for a `scope` field:
   + `@default`
   +  `@dedicated`
   + a string.  This string is essentially a 'group-by' key of resources into a file that has this string as an identifier.

What do you think?

**Comment by kaufers** [comment]
@chungers Updated example:
```
{
  "resource" : {
    "softlayer_virtual_guest": {  
      "host": {...}
    }
    "softlayer_file_storage": {
      "worker_fs": {
        “@scope”: “@dedicated",
        ...
      }
    },
    "softlayer_block_storage": {
      "shared_block_storage": {
        “@scope”: “managers”,
        ...
      }
    }
}
```

This created 3 files:
```
$ ls -l
total 24
-rw-r--r--  1 kaufer  staff  330 Jun  2 14:48 instance-1234.tf.json
-rw-r--r--  1 kaufer  staff  296 Jun  2 14:48 instance-1234-dedicated.tf.json
-rw-r--r--  1 kaufer  staff  170 Jun  2 14:48 scope-managers.tf.json
```

```
$ cat instance-1234.tf.json 
{
    "resource": {
      “softlayer_virtual_guest": {
        "instance-1234": {
          "tags": {
            "infrakit.attach”: [  <-- Filename of the associated `tf.json` files
              “instance-1234-dedicated”,
              “scope-managers”
            ] 
          },
          ...
        }
      }
    }
  }
```
```
$ cat instance-1234-dedicated.tf.json 
{
    "resource": {
      “softlayer_file_storage": {
        "instance-1234-worker_fs": {...}
      }
    }
  }
```
```
$ cat scope-managers.tf.json
{
    "resource": {
      "softlayer_block_storage": {
        "managers-shared_block_storage": {...}
      }
    }
  }
```

**Comment by chungers** [comment]
Some comments on this part:

```
$ cat instance-1234.tf.json 
{
    "resource": {
      “softlayer_virtual_guest": {
        "instance-1234": {
          "tags": {
            "infrakit.attach”: [  <-- Filename of the associated `tf.json` files
              “instance-1234-dedicated”,
              “scope-managers”
            ] 
          },
          ...
        }
      }
    }
  }
```

How about something like this:

```
$ cat instance-1234.tf.json 
{
    "resource": {
      “softlayer_virtual_guest": {
        "user-provided-name": {         <-- I think this name gets replaced with the generated id right?
          "tags": {
            "infrakit.attach”: [  <-- Filename of the associated `tf.json` files
              “@dedicated”,  <-- since we don't know the id at the time of definition, just use this symbol to signify the file instance-xyz-dedicated.tf.json
              “managers”  <-- this will resolve to `scope-managers.json` file.
            ] 
          },
          ...
        }
      }
    }
  }
```
What do you think?  This has the benefit of being consistent with the `@scope` field.  In fact the allowed values are the same.  So it's easier to figure out what's going on.

**Comment by chungers** [comment]
Sorry I got confused.  I forgot you are showing the `tf.json` *after* they are created.  Therefore, the instance ids will have been known and the attach tag should have the full filenames.

**Comment by kaufers** [comment]
@chungers Now that the SPI has been updated to pass the `RollingUpdate` context we need to figure out the naming convention issue here: https://github.com/docker/infrakit/issues/561#issuecomment-305282790

The basic problem is when we have `instance-1234` with dedicated resource `worker-fs-1234` and issue a rolling update. We will remove `instance-1234` but leave the dedicated `worker-fs-1234` resource.

We need to know that the replacement instance (call it `instance-5678`) should wire up to use the existed dedicated `worker-fs-1234` resource.

Seems like the group plugin (that knows the it just destroyed `instance-1234` with `RollingUpdate`) needs to pass that context on the next provision. Any ideas how we should handle this?
 
Maybe set the `LogicalID` to the original `instance-1234`?
Or add a custom tag?
Or update the `instance.Spec` with a new prop that contains the previous ID?
Or use the `Attachments` prop?

Thanks!
