### ISSUE TITLE
Autoscaling groups + LB support

### ISSUE THREAD

**Issue by odzhu** [docker/infrakit#581]
Hi Team,

I like the idea of the product overall, however, as I understand the concept,
infrakit works with VM instances directly(scale, health check, update etc) and not leverages ASG for this.

While this is ok with libvirt, vagrant or maas,
Lot's of this functionality is natively supported by public cloud providers.

Using LB + autoscaling group is a common pattern for building "cattle apps" and now infrakit seems reinvents a wheel here and adds a point of failure/maintenance.

Is there any way to describe desired state for autoscaling groups + flavor and potentially manage them with group plugin ?

Again, please excuse me if I miss it in the documentation .

**Comment by chungers** [comment]
@odzhu  thanks for your comment.   

> While this is ok with libvirt, vagrant or maas,
Lot's of this functionality is natively supported by public cloud providers.

Many of the use cases we now focus are actually for on-prem, bare-metal environments.  As you have pointed out, infrakit brings the elasticity of public cloud to these environments.   One of the goals of the group controller in infrakit is to provide autoscaling group-like functionality regardless of the environment you are running on, public cloud or on-premise. 

We have plans to build out integration with LB - either in public cloud (e.g. AWS ALB or ELB) or on-prem (eg. F5).  We want to support the common pattern LB+autoscaling group regardless of the environment you're in.  So your Swarm or k8s cluster can have cluster autoscaling capabilities on AWS or in your own private data center.

> Using LB + autoscaling group is a common pattern for building "cattle apps" and now infrakit seems reinvents a wheel here and adds a point of failure/maintenance.

There are some subtle differences between our group controller and, for example, AWS autoscaling group.  We have requirements to support where when a member of the group is upgraded (to a larger instance, for example), we need to retain the volume for the instance and reattach the volume to the new instance.  This is important to us for use cases like maintaining Docker Swarm manager state (in `/var/lib/docker`) so that the quorum doesn't think the topology has changed when a manager node is updated.    In this particular case, the extra POF/maintenance is hopefully minimal because infrakit is actually embedded as a part of the quorum itself so it's in the same control plane.  Having infrakit actually makes this control plane resilient on its own (without relying on another autoscaling group implementation).

There are also use cases such as supporting checkpointing and restore (CRIU) of container states on workers where you need to retain the volume and reattach even when they are considered members of a scaling group.  These are some of the limitations we ran into working with autoscaling groups in public clouds that we would like to address with our implementation.   

Having said that, there's a way to use AWS's ASG with infrakit, if you don't care about reattaching volumes, and it is simpler and does make sense to defer the control over to their ASG implementation, as you suggested. 

> Is there any way to describe desired state for autoscaling groups + flavor and potentially manage them with group plugin ?

We are doing some work on the group controller right now to make it look even more like an ASG and there's some work in at least the AWS instance plugin that exposes the ASG as a resource.  We hope to soon be able to have a single yaml file that has a mix of infrakit-native group spec and specs for, for instance, AWS autoscaling group.  So you can mix and match to suit your requirements.  Is this what you have in mind?

**Comment by mgpoly** [comment]
@odzhu @chungers hi, I just completed some work adding support for AWS ASG as an instance plugin (continuing the initial skeletal work).  I will submit it shortly (just need to test support for reporting ASG details, test destroy function).

**Comment by mgpoly** [comment]
@odzhu @chungers update, here's current pull request:
https://github.com/docker/infrakit.aws/pull/40
There's issues around code coverage/testing I'll have to look into -- not sure how they were passing as the module wasn't working before.

Note that, the patch will create ASGs, however there's still a big gap: how docker swarm drain command is to be handled.  Currently the ASG plugin will delete the ASG but it won't issue swarm drain to the underlying instances.  So if you then execute 'docker node ls' you'll see some nodes as unreachable.  I'm not sure what the 'InfraKit' way to handle this would be.

**Comment by odzhu** [comment]
@chungers @mgpoly thank you for the insight, you covered all of my question, will continue playing with the app.
