### ISSUE TITLE
Race condition on manager leadership detection

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#627]
The manager plugin is active and able to respond to the `Manager.IsLeader` RPC call before it has determined leadership (and then returns `false` by default).

Can we either block the manager startup (so it is not advertised) until the leadership is determined or have the API return some type of unknown status?

Currently, the terraform plugin checks leadership prior to running `apply` and we have hit issues where `apply` does not run because the manager plugin says that it is not the leader; the logs show that the RPC `IsLeader` call is processed prior to determining swarm leadership.

**Comment by chungers** [comment]
Doesn't the RPC `IsLeader` eventually return 'true' if the node is indeed the leader?  AFAICT apply runs periodically right?  So if it misses one iteration wouldn't it eventually run?

**Comment by kaufers** [comment]
@chungers In the terraform plugin, the apply goroutine will exit if the node is not the leader: 
https://github.com/docker/infrakit/blob/master/pkg/provider/terraform/instance/apply.go#L115

This means that the `group commit` RPC call will be successful but `terraform apply` will not actually get executed because the goroutine will be created and then immediately stop:
https://github.com/docker/infrakit/blob/master/pkg/provider/terraform/instance/apply.go#L37-L47

Can we just block the manager plugin from starting until leadership detection is done? If so, then the terraform plugin would get an error when it tries to find the manager and then sleep/retry:
https://github.com/docker/infrakit/blob/master/pkg/provider/terraform/instance/apply.go#L40

**Comment by chungers** [comment]
How about not let the apply goroutine exit https://github.com/docker/infrakit/blob/master/pkg/provider/terraform/instance/apply.go#L47?  

This way there's no complex coordination between the terraform plugin and manager/group controller.   If the apply isn't executed because leadership isn't certain, then x seconds later, once leadership is determined, the apply will be executed.  

Also, I don't think exiting the goroutine would work right?  Let's say this node was a leader for a while... and then it lost leadership...  the goroutine thus exits... But if later on, leadership comes back to this node (and this is entirely possible and not that unusual), how do we restart that goroutine?   I think the code is simpler just to loop it forever, and do work only if leadership is certain.  This way, if we missed the leadership determination in one iteration, we can always catch up the next time we are certain the node is the leader.    Thoughts?

**Comment by kaufers** [comment]
@chungers I like it, thanks for the feedback; I'll push up a PR with the change to never exit the goroutine.
