### ISSUE TITLE
Generic key-value swarm config storage

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#646]
When creating the swarm, we persist configuration data in a `.json` file on the manager. That file is then `source`'d when executing a `infrakit manager commit ...` command; some of the files are:

* `my-vars.json`:
```
{
  "cluster_swarm_worker_use_nfs": true,
  "cluster_swarm_worker_size": 5,
  ...
}
```
* `common.ikt`: 
```
{{ $vars := (source "my-vars.json" | jsonDecode) }}
{{ var "/cluster/swarm/worker/size" $vars.cluster_swarm_worker_size }}
{{ var "/cluster/swarm/worker/use/nfs" $vars.cluster_swarm_worker_use_nfs }}
...
```

The worker size is `templated`'d into the group spec. But, we use this `bool` "use_nfs" value to dynamically include a resource type in the group's terraform instance definition, for example:

```
{{ source "common.ikt" }}
{
  "ID": "workers",
  "Properties": {
    "Allocation": {
      "Size": {{ var "/cluster/swarm/worker/size" }},
    }
    "Instance": {
      "Plugin": "instance-terraform",
      "Properties": {
        "resource": {
          "ibm_compute_vm_instance": {
            "host": {
              ...
            }
          }
{{ if var "/cluster/swarm/worker/use/nfs" }}
          ,"ibm_storage_file": {
            ...
          }
{{ end }}
...
```

This allows us to have a single group definition that can dynamically include an NFS volume. We want to be able to update this at runtime (for example using a docker storage plugin).

In order to do this we need to:
1. Manually edit the json `vars` file
2. Issue another `manager commit`

We'd like to switch to using a command like:
```
# infrakit manager change -v Groups/workers/Properties/Properties/Allocation/Size=3
```

However, this only works for attributes **in** the group spec, it does not work for attributes that **control template logic** in the group spec.  If we used the `infrakit manager change` command to update the group size then the backing json `vars` file is out of sync.

How can infrakit manage group attributes that are not part of the group spec? Do we need to create a metadata plugin for this?

**Comment by chungers** [comment]
I think in this case, when the nfs flag is set to true -- there is actually a structural change to the spec JSON itself..    So your manual process of editing the json `vars` file and then `commit` is correct as it will render a new Spec and that Spec will be stored in the quorum.

I do see your point about wanting to be able to change the var via `change` since you can have multiple `-v` and they are grouped together like a single 'change list'.  So we would want to represent this value at some path within the spec itself.

I don't think creating a metadata plugin just so you can change some value which then affects rendering of a template is a good approach... it's too tedious.   The existing edit/commit cycle isn't ideal either -- as it represents two separate workflows (that vs the `change` command).

Currently, the spec that's committed and persisted in the quorum is a *rendered* view.  That's a reasonable first try but as you pointed out, it doesn't have the expressiveness/ convenience of the `change` command because it requires the tedious edit/commit cycle when we have already have all this flexibility of using templates that are data-driven by a limited set of *state variables* (which is your `vars.json` file).

Here is an idea: one way to solve this is two change the way we store the spec -- we separate the *state variables* from the templates.  So instead of storing a rendered view (the final spec), we store the *vars* and the *template*, because the final spec can always be computed from these two inputs.  Then `change` becomes a way for user to modify one or more simple parameters (and not paths that reflect the nesting of structures in our schema) and commit those changes in a single commit.    What do you think?  
 
This would take a bit of work but would be pretty cool.  It can decouple the structure of the spec from what the end user care about -- a smallish set of variables that they want to change.  And then everything else is driven by those parameters.

**Comment by kaufers** [comment]
@chungers I like your proposal. So then would our backend `vars` file become unnecessary after the initial commit?

When the template engine runs it is using the `vars` file as a data source -- would that data source simply become the vars persisted in the swarm?

**Comment by kaufers** [comment]
Pretty sure that this is completed with the `vars` plugin, thanks @chungers
