### ISSUE TITLE
Issue with communication with Leader node from non-leader managers

### ISSUE THREAD

**Issue by wongwill86** [docker/infrakit#763]
Hello,
As discussed in the slack channel, I'm having trouble with a couple of commands from non-leader managers.

An example is this:
```
root@ip-172-31-53-20:/home/ubuntu# docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /infrakit:/infrakit -e INFRAKIT_HOME=/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -e INFRAKIT_CLIENT_TIMEOUT='60s' infrakit/devbundle:latest infrakit manager leader --log 5 --log-debug-V 900
DBUG[11-14|10:07:46] Found manager                            module=cli/manager name=group leader=false fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
CRIT[11-14|10:07:46] error executing                          module=main cmd=infrakit err="Cannot perform manager operations on a non-leader node" fn=main.main
Cannot perform manager operations on a non-leader node
```

I've tried to pare down as much from the examples repo as possible to get the smallest test setup:

Steps:
1. Create 2 AWS nodes with security group with all traffic open within the security group.
1. On all nodes install docker and create/join swarm.
```
root@ip-172-31-61-152:/home/ubuntu# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
632b7g05qxl4lgyk2tsyvqehx     ip-172-31-53-20     Ready               Active              Reachable
520dp6nkdlrl6cz5f03z1izpb *   ip-172-31-61-152    Ready               Active              Leader
```
2. On both nodes, run
```
docker run -d --restart always --name infrakit -p 24864:24864 -v /var/run/docker.sock:/var/run/docker.sock -v /infrakit:/infrakit -e INFRAKIT_HOME=/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -v /var/log/:/var/log -e INFRAKIT_MANAGER_BACKEND=swarm -e INFRAKIT_ADVERTISE=172.31.61.152:24864 -e INFRAKIT_CLIENT_TIMEOUT='60s' -e INFRAKIT_TAILER_PATH=/var/log/cloud-init-output.log infrakit/devbundle:latest infrakit plugin start manager group vars combo swarm time tailer ingress --log 5 --log-debug-V 900
```
3. check connectivity
```
root@ip-172-31-61-152:/home/ubuntu# nc -z -v 172.31.53.20 24864
Connection to 172.31.53.20 24864 port [tcp/*] succeeded!
```
and
```
root@ip-172-31-53-20:/home/ubuntu# nc -z -v 172.31.61.152 24864
Connection to 172.31.61.152 24864 port [tcp/*] succeeded!
```
4. Check leadership on first node (works):
```
root@ip-172-31-61-152:/home/ubuntu# docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /infrakit:/infrakit -e INFRAKIT_HOME=/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -e INFRAKIT_CLIENT_TIMEOUT='60s' infrakit/devbundle:latest infrakit manager leader --log 5 --log-debug-V 900
DBUG[11-14|10:25:22] Found manager                            module=cli/manager name=group leader=true fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
DBUG[11-14|10:25:22] Found manager                            module=cli/manager name=group a
ddr=/infrakit/plugins/group fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
DBUG[11-14|10:25:22] Found updatable                          module=cli/manager name=group addr=/infrakit/plugins/group fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
IsLeader       : true
LeaderLocation : http://172.31.61.152:24864
```
5. check leadership on second node (error message from top of post)

6. also tried adding a 3rd node in case there needed be a majority of some sort but still didn't work.

If i set the remotes with `... infrakit remote set remote set mycluster 172.31.61.152:24864,172.31.53.20:24864 ` and call manager leader with `-e INFRAKIT_HOST=mycluster` it works fine.

I noticed in the logs of the second node:
```
DBUG[11-14|10:28:19] Lost leadership. updating forwarding URL module=rpc/mux url=http://172.31.61.152:24864 err=nil V=100 fn=github.com/docker/infrakit/pkg/rpc/mux.NewServer.func1
```

i'm not sure if this is also related but i can't seem to get vars to persist across manager (maybe related since i remember reading the vars should be persisted in swarm's raft quorum)
i.e.
One first node (which is also the leader):
```
root@ip-172-31-61-152:/home/ubuntu# docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /infrakit:/infrakit -e INFRAKIT_HOME=/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -e INFRAKIT_CLIENT_TIMEOUT='60s' infrakit/devbundle:latest infrakit vars change mykey=myvalue -c --log 5 --log-debug-V 900
Committing 1 changes, hash=4c74fbb88d6a80353241f27ae569b898
{
  "mykey": "myvalue"
}
root@ip-172-31-61-152:/home/ubuntu# docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /infrakit:/infrakit -e INFRAKIT_HOME=/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -e INFRAKIT_CLIENT_TIMEOUT='60s' infrakit/devbundle:latest infrakit vars keys --log 5 --log-debug-V 90
mykey
```
On Second node (doesn't work if i specify `INFRAKIT_HOME=mycluster` either):
```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /infrakit:/infrakit -e INFRAKIT_HOME=/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -e INFRAKIT_CLIENT_TIMEOUT='60s' infrakit/devbundle:latest infrakit vars  keys --log 5 --log-debug-V 900
```

Please let me know if i'm missing something or if you want me to try something out.

Thanks!

**Comment by chungers** [comment]
The infrakit containers on the managers need to run with `-p 24864:24864` (which you did) and the client needs to talk to that port instead of talking to the local socket (which you were doing by pointing to the same `INFRAKIT_HOME` bind mount).

Try this... from a host (eg. your workstation), do `infrakit remote add mycluster ip1:24864` where `ip1` is the public IP address of the manager1.    Now do
```
INFRAKIT_HOST=mycluster infrakit plugin ls
```
from your local machine.  Does it show the remote plugins?   If that works try changing the IP now to the other manager (via `infrakit remote set mycluster ip2:24864`).   Now does it work?

I will try to replicate your issue and update this with the steps.

**Comment by wongwill86** [comment]
Yes it looks like when I use the `INFRAKIT_HOST=mycluster` it correctly lists out the plugins from all instances. But `infrakit manager leader` has the same error as if I ran it locally on that machine.

Outputs:

From my local host machine:
Set `ip1` to the leader's public ip address.
```
$ docker run --rm    -v /var/run/docker.sock:/var/run/docker.sock -v infrakit:/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -v /var/log/:/var/log -e INFRAKIT_CLIENT_TIMEOUT='60s' -e INFRAKIT_HOST=mycluster infrakit/devbundle:latest infrakit plugin ls  --log 5 --log-debug-V 900
INTERFACE           NAME                          LISTEN
Flavor/0.1.0        combo                         http://ip1:24864/combo/
Group/0.1.0         group-stateless               http://ip1:24864/group-stateless/
Metadata/0.1.0      group-stateless               http://ip1:24864/group-stateless/
Updatable/0.1.0     group/status                  http://ip1:24864/group/
Updatable/0.1.0     group/vars                    http://ip1:24864/group/
Controller/0.1.0    group                         http://ip1:24864/group/
Group/0.1.0         group                         http://ip1:24864/group/
Manager/0.1.0       group                         http://ip1:24864/group/
Updatable/0.1.0     group                         http://ip1:24864/group/
Controller/0.1.0    ingress/                      http://ip1:24864/ingress/
Flavor/0.1.0        swarm/manager                 http://ip1:24864/swarm/
Metadata/0.1.0      swarm/manager                 http://ip1:24864/swarm/
Flavor/0.1.0        swarm/worker                  http://ip1:24864/swarm/
Metadata/0.1.0      swarm/worker                  http://ip1:24864/swarm/
Event/0.1.0         tailer                        http://ip1:24864/tailer/
Metadata/0.1.0      tailer                        http://ip1:24864/tailer/
Event/0.1.0         time/streams                  http://ip1:24864/time/
Metadata/0.1.0      time                          http://ip1:24864/time/
$ docker run --rm    -v /var/run/docker.sock:/var/run/docker.sock -v infrakit:/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -v /var/log/:/var/log -e INFRAKIT_CLIENT_TIMEOUT='60s' -e INFRAKIT_HOST=mycluster infrakit/devbundle:latest infrakit manager leader --log 5 --log-debug-V 900
DBUG[11-15|18:03:45] Found manager                            module=cli/manager name=group leader=true fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
DBUG[11-15|18:03:45] Found manager                            module=cli/manager name=group addr=http://54.164.138.110:24864/group/ fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
DBUG[11-15|18:03:45] Found updatable                          module=cli/manager name=group addr=http://54.164.138.110:24864/group/ fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
IsLeader       : true
LeaderLocation : http://172.31.61.172:24864
```

Set `ip1` to a non leader node:
```
$ docker run --rm    -v /var/run/docker.sock:/var/run/docker.sock -v infrakit:/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -v /var/log/:/var/log -e INFRAKIT_CLIENT_TIMEOUT='60s' -e INFRAKIT_HOST=mycluster infrakit/devbundle:latest infrakit plugin ls  --log 5 --log-debug-V 900
INTERFACE           NAME                          LISTEN
Flavor/0.1.0        combo                         http://ip1:24864/combo/
Group/0.1.0         group-stateless               http://ip1:24864/group-stateless/
Metadata/0.1.0      group-stateless               http://ip1:24864/group-stateless/
Updatable/0.1.0     group/status                  http://ip1:24864/group/
Updatable/0.1.0     group/vars                    http://ip1:24864/group/
Controller/0.1.0    group                         http://ip1:24864/group/
Group/0.1.0         group                         http://ip1:24864/group/
Manager/0.1.0       group                         http://ip1:24864/group/
Updatable/0.1.0     group                         http://ip1:24864/group/
Controller/0.1.0    ingress/                      http://ip1:24864/ingress/
Flavor/0.1.0        swarm/manager                 http://ip1:24864/swarm/
Metadata/0.1.0      swarm/manager                 http://ip1:24864/swarm/
Flavor/0.1.0        swarm/worker                  http://ip1:24864/swarm/
Metadata/0.1.0      swarm/worker                  http://ip1:24864/swarm/
Event/0.1.0         tailer                        http://ip1:24864/tailer/
Metadata/0.1.0      tailer                        http://ip1:24864/tailer/
Event/0.1.0         time/streams                  http://ip1:24864/time/
Metadata/0.1.0      time                          http://ip1:24864/time/
$ docker run --rm    -v /var/run/docker.sock:/var/run/docker.sock -v infrakit:/infrakit -e INFRAKIT_PLUGINS_DIR=/infrakit/plugins -v /var/log/:/var/log -e INFRAKIT_CLIENT_TIMEOUT='60s' -e INFRAKIT_HOST=mycluster infrakit/devbundle:latest infrakit manager leader --log 5 --log-debug-V 900
DBUG[11-15|18:05:26] Found manager                            module=cli/manager name=group leader=false fn=github.com/docker/infrakit/cmd/infrakit/manager.Command.func1
CRIT[11-15|18:05:26] error executing                          module=main cmd=infrakit err="Cannot perform manager operations on a non-leader node" fn=main.main
Cannot perform manager operations on a non-leader node
````

**Comment by wongwill86** [comment]
Not sure if this will be useful but here are the first 200 lines of logs of the leader node:
https://gist.github.com/wongwill86/2e42e70a0a492724b8118e9e6d8dd9f3
and non leader node:
https://gist.github.com/wongwill86/d4e6f35b942b4f3e3c52d28055bf449b

**Comment by chungers** [comment]
Hm...  I can't repro the problem, but let me document this here and hopefully it helps:

### Set Up

1. Two Ubuntu hosts: 18.195.118.96 (private IP 172.31.17.134) and 52.57.235.41 (private IP 172.31.29.6)
2. Install docker on each one: `curl -sSL https://get.docker.com | sh`
3. On 18.195.118.96, do `docker swarm init` to make it the leader.
4. On 52.57.235.41 do 
```
docker docker swarm join --token SWMTKN-1-47dfzymux8yrsnb1j5f8bh418oi6ekeiy7mp97kx7c76ot1px3-amnfr0ahg03w8rdd738v5orf5 172.31.17.134:2377
```
Now we have a swarm with managers:
```
root@ip-172-31-17-134:~# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
agxabv4ua8pvm801qchjrdxka *   ip-172-31-17-134    Ready               Active              Leader
y6qhf5z6ke9jt4xdedsraxhkz     ip-172-31-29-6      Ready               Active              Reachable
```
### Infrakit

Infrakit does request forwarding when there's a `INFRAKIT_ADVERTISE` environment variable set and the `manager` is started as well.  This is because the `manager` will listen on port 24864 and knows about which node is the leader.  The manager will start a 'mux' that supports remote RPC calls and request forwarding if the manager isn't a leader:

On host 18.195.118.96 (private IP 172.31.17.134):
```
docker run -d --restart always --name infrakit -p 24864:24864 \
-v /var/run/docker.sock:/var/run/docker.sock \
-e INFRAKIT_MANAGER_BACKEND=swarm \
-e INFRAKIT_ADVERTISE=172.31.17.134:24864 \
infrakit/devbundle:latest infrakit plugin start manager group vars --log 5 --log-debug-V 900
```
On host 52.57.235.41 (private IP 172.31.29.6):
```
docker run -d --restart always --name infrakit -p 24864:24864 \
-v /var/run/docker.sock:/var/run/docker.sock \
-e INFRAKIT_MANAGER_BACKEND=swarm \
-e INFRAKIT_ADVERTISE=172.31.29.6:24864 \
infrakit/devbundle:latest infrakit plugin start manager group vars --log 5 --log-debug-V 900
```
Notes:
  + We use the *private IP* in the `INFRAKIT_ADVERTISE` -- this will allow infrakit to forward traffic inside a DMZ without using outside public IP addresses.
  + We need to make sure port 24864 is open *at least* on the inside.

### Remote Client
On your workstation, do
```
infrakit remote set test 18.195.118.96:24864
```
Now you should see:
```
$ INFRAKIT_HOST=test INFRAKIT_CLIENT_TIMEOUT=5s infrakit manager leader
IsLeader       : true
LeaderLocation : http://172.31.17.134:24864
```

On host 18.195.118.96 (private IP 172.31.17.134), now do a swarm leave to force the leadership to change to 52.57.235.41 (private IP 172.31.29.6):

```
# docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
8in2lui8zg1oncancj7s1cnd3 *   ip-172-31-17-134    Ready               Active              Reachable
y6qhf5z6ke9jt4xdedsraxhkz     ip-172-31-29-6      Ready               Active              Leader
```

Now, our local INFRAKIT_HOST points to a host that is no longer leader.  We shouldn't have to 
find out which host has become the new leader:
```
$ INFRAKIT_HOST=test INFRAKIT_CLIENT_TIMEOUT=5s infrakit manager leader
IsLeader       : true
LeaderLocation : http://172.31.29.6:24864
```

So here the request to a non-leader manager was forwarded to the leader node (because it answered `isLeader: true`.

On the host 18.195.118.96 (private IP 172.31.17.134), we can test too:

```
docker run --rm -v $(pwd):/infrakit infrakit/devbundle:latest infrakit remote set test 172.31.17.134:24864
```
This sets up the remotes (you should see a `hosts` file at `$(pwd)`).

```
root@ip-172-31-17-134:~# docker run --rm -v $(pwd):/infrakit -e INFRAKIT_HOST=test infrakit/devbundle:latest infrakit manager leader
IsLeader       : true
LeaderLocation : http://172.31.29.6:24864
```

I hope this example helps.   This is tested with the latest on master.

**Comment by wongwill86** [comment]
hrmm ok I think I know what the issue is.
The first mistake I did was with my example was that I set `INFRAKIT_ADVERTISE` to the leader ip address. I followed your example to set  to it's **own** private ip address vs before i set it to the leader ip address and the leader is resolved on the second node. But this wasn't really the issue I was trying to figure out.

The second mistake was that I assumed that on a non-leader node, I could simply mount/share `INFRAKIT_HOME` between the container running the infrakit plugins and any container I want to run an infrakit command.
i.e. I was hoping this would work:
Start infrakit with 
```
docker run --rm -v /infrakit:/infrakit \
-v /var/run/docker.sock:/var/run/docker.sock \
-e INFRAKIT_HOME=/infrakit  \
-e INFRAKIT_CLIENT_TIMEOUT=5s -e INFRAKIT_ADVERTISE=172.31.49.162:24864 \
infrakit/devbundle:latest  infrakit manager leader --log 5 --log-debug-V 900
```
Query manager leader (mounting `INFRAKIT_HOME`) with:
```
docker run --rm -v /infrakit:/infrakit \
-v /var/run/docker.sock:/var/run/docker.sock \
-e INFRAKIT_HOME=/infrakit  \
-e INFRAKIT_CLIENT_TIMEOUT=5s \
infrakit/devbundle:latest  infrakit manager leader --log 5 --log-debug-V 900
```

Oddly enough this *will work* when running on the Leader node but not a non-leader node.

But I guess I probably missed your point of using `infrakit remote set` and `INFRAKIT_HOST`. So far as long as I use infrakit remote (even just to the same local machine it's running on) it works.

Thanks!

**Comment by chungers** [comment]
Yeah sorry much of this confusion came from poor (or the lack of) documentation.

Your case of running infrakit on the leader manager node works by mounting the same INFRAKIT_HOME is because it most likely just talked to the leader via the socket.  That will always work because you're just talking to local unix socket (see the socket files in /infrakit/plugins).   The tricky part is how you can get a non-leader node to forward the requests it received to another infrakit running on a different host.  The only way is if the nodes are all listening on TCP -- that's why you'd have to set the advertise IP address and have a port open.   Once you have that set up it will work.

At some point you may wonder how to secure the connection from your local computer to the remote cluster.  That's where the ssh tunneling comes in.  To do that simply use the `--ssh-user` and `--ssh-addr` flags of `infrakit remote set`.   The ssh-user is self-explanatory... it's the user that has can log into one of the manager hosts via ssh (using public/private key).  The `ssh-addr` flag is the *public* IP address of one of the manager hosts.  When you do that only port 22 needs to be open and not 24864.  The client will create a SSH tunnel locally to connect to the infrakit daemon running behind the firewall on the remote host.
