### ISSUE TITLE
Rolling Updates and Enrollment

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#782]
We are using the IBM Cloud auth plugin https://github.com/docker/infrakit/blob/master/pkg/provider/ibmcloud/plugin/instance/volumeauthplugin.go to handle manager authorizations against an NFS volume.

The enrollment controller is querying the terraform instance provider for group membership and, on a rolling update of the `managers` group, we are losing NFS auth on the current manager.

During a rolling update of the `managers` group:
1. Group controller executes a `DescribeInstances` on the terraform instance provider
2. Group controller picks `mgr` (which also happens to be the leader) for deletion and issues a `Destroy`
3. Terraform provider removes the `tf.json` file for this instance and starts the deletion
4. Enrollment controller gets the updated members of the `managers` group, sees that `mgr1` is no longer in the group, and deauthorizes it from NFS
5. Current leader is no longer authorized to NFS and bad things happen

The problem is that `mgr1` is still the leader and really has not been removed yet (the backend cloud will take a minute or so to power down the VM).

Is there any way that we either:
1. Not delete the current leader on a `manager` rolling update (ie, issue rolling updates for the non-leader nodes first, change leadership, and then do the last rolling update)
2. Prevent the enrollment controller from even running during a rolling update an associated group?

**Comment by chungers** [comment]
There are two parts as you described:

1. Correct ordering of rolling updates  -- See comment in #783 
2. Enrollment controller needs to know a rolling update is happening

### Enrollment controller's knowledge of rolling update
I think this is necessary so the enrollment controller can temporarily disable removing any of what it perceives as orphaned NFS authorizations.  The assumption here is that whatever the id that was used to create the NFS authorizations remains the same after the manager has been updated.  Can you confirm this is the case @kaufers ?    For example, an IP address of the manager was used and the same IP remains after the replacement comes up.

There are different ways for the enrollment controller to know the cluster is in the middle of an update -- via rpc call to it or storing this information in a store that accessible to it.   I favor the latter because rpc calls to lock/unlock the enrollment controller are just stuck authorizations waiting to happen.  

A better approach would be to have the enrollment controller check the centralized state before it tries to deauthorize anything.   So it determined that `mgr1` needs to be de-authorized, but prior to issuing a `Destroy` to the instance plugin, it checks the centralized transaction log and see that the node is pending update and backs off.   This behavior can be gated even by a 'policy' we can add to the schema/config of the enrollment controller so that for cases where the instance identities do change (e.g. with workers identified by infrastructure id), it can go ahead with the `Destroy`.

As for the 'centralized state', I am wondering if we can leverage the existing vars / metadata infrastructure.  We can technically have a dedicated vars plugin (running in a different name maybe `updating`) and have that writing into the Swarm raft quorum.   Before issuing a `Destroy` of a NFS auth, the enrollment controller tries to read a metadata entry at `updating/mgr1-id` and if it sees that it's there, then it backs off.  If that read times out, it's realizing that maybe the node disappeared not as part of update or maybe the node is a worker and in that case it just goes ahead and issues a `Destroy` to deauthorize.  

This has the simplicity of leveraging everything that's already built.  This additional `updating` metadata plugin that is running could even store the state necessary for #783.

Thoughts?

**Comment by kaufers** [comment]
@chungers 

> The assumption here is that whatever the id that was used to create the NFS authorizations remains the same after the manager has been updated. Can you confirm this is the case @kaufers ? For example, an IP address of the manager was used and the same IP remains after the replacement comes up.

The NFS auth plugin uses the VM ID (since the backend API is authorizing a _specific_ volume to a _specific_ VM). So the instance's `SourceKeySelector` **will not** be the same when the replacement comes up.

> Thoughts?

I like using the `vars` plugin to store this. 👍 

Let me know how I can help implement this.

**Comment by chungers** [comment]
@kaufers  here are some ideas:

1. We can add a new struct field here (let's make up a name, see below): https://github.com/docker/infrakit/blob/master/pkg/controller/enrollment/types/types.go#L103   As example:
```json
"Options" : {
   "PolicyNoDestroyIfMetadataExists" : "updating",
}
```
Given this, the code in the enrollment controller ([here](https://github.com/docker/infrakit/blob/master/pkg/controller/enrollment/sync.go#L199)) will then make a call to check a metadata path that is based on this value as a prefix and the instance id that is about to be destroyed.  In this example, it'd check for metadata `updating/<group_name>/<instance_id>` and if this metadata key exists, then we know this particular node is in the middle of an update.   We can get the `<group_name>` because the enrollment controller associates a group to an instance plugin (the NFS authorizer).  So we don't destroy the association if and only if there's such entry.  Otherwise, we proceed with destroying the association.  The value `updating` already has the context built-in: we'd have a metadata plugin with namespace `updating` if and only if an updating is indeed in progress.  In the case of destroy, the assumption is that we'd never destroy in the middle of a rolling update, so we would not be able to get a value with `updating` as the path.

To query the metadata, consider making some changes to the enroller so that instead of a `plugins` field, we have a [`scope.Scope`](https://github.com/docker/infrakit/blob/master/pkg/run/scope/scope.go#L38) here: https://github.com/docker/infrakit/blob/master/pkg/controller/enrollment/enroller.go#L36  Once the `scope` is plumbed through from [here](https://github.com/docker/infrakit/blob/master/pkg/run/v0/enrollment/enrollment.go#L74), you can make a metadata query via the scope's `Metadata` function or use a helper function with timeout (if we don't want to block forever) like [so](https://github.com/docker/infrakit/blob/master/pkg/run/scope/metadata_test.go#L118).

Let me know what you think.  We can make up whatever path we need to query here.  This is partly to inform how we should be writing the records during rolling update and partly to decouple implementations into different PR's.

**Comment by kaufers** [comment]
@chungers This sounds like a good first pass; I'll work on a PR for this

**Comment by chungers** [comment]
@kaufers  - Does #826 address this issue?   I think there's a remaining point on leader not self-destruct which is addressed in #805.  There's still the issue of the un-updated leader transferring leadership over to a new leader (which is a node that has been updated).  I am looking at implementing that.

**Comment by kaufers** [comment]
@chungers I think that #805 should address this; as long as a `Destroy` on `self` is prevented then we do not need to worry about loosing auth. Agree?

**Comment by chungers** [comment]
#805 will leave the leader out of the updates so only N-1 nodes are updated.  This should leave the NFS authorizations intact.   Please verify and close this issue?   

Now actually updating the very last node (the leader) will come in a separate PR; probably worthy of a specific issue to track...

**Comment by kaufers** [comment]
Yes, #805 covers this issue.

**Comment by kaufers** [comment]
@chungers new issue https://github.com/docker/infrakit/issues/838
