### ISSUE TITLE
Rolling updates of the manager nodes

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#783]
We are running Infrakit on the swarm manager nodes and want to issue a rolling update of `managers` group.

**It appears that Infrakit is not waiting for each manager to complete before proceeding to the next node.**

Note that we are using block storage to backup `/var/lib/docker` and re-using the same IP address for each manager. This means that, during a rolling update of a manager node, the node is not removed from the swarm (so `docker node ls` still shows it).

A possible issue is that the `Destroy` is asynchronous and that the `DescribeInstances` nodes have no status attribute (like "provisioning" or "complete"). Here's what the flow looks like:

1. Group controller issues a `DescribeInstances` and gets instances with Logical ID values of `mgr1`, `mgr2`, `mgr3`
2. Group controller issues a `Destroy` on node with Logical ID of `mgr1` and then issues a `Provision` with a Logical ID of `mgr1`
3. The next `DescribeInstances` poll cycle from the group controller gets instances with Logical ID values of `mgr1`, `mgr2`, `mgr3`. In this case the "new" `mgr1` is not yet provisioned -- moreover, the "old" `mgr1` is probably still even online since the backend cloud VM destroy takes a minute or so to power down the VM (which means that the swarm node is still `ready` and `available`)
4. Group controller issues a `Destroy` on node with Logical ID of `mgr2` ... etc.

Do we need to return some "provisioning status" on the `DescribeInstances` so that the group controller can determine if a node still being provisioned or if it is complete?

**Comment by chungers** [comment]
This is related to #782.  There are parts to this process for managers.   For managers, we assume parallelism of 1 which means one sequential thread of updates for this entire group.

  + Ordering of rolling update for managers
  + Ensuring proper replacement before continuing -- this includes health-check (e.g. new manager joins the swarm)
  + Transferring leadership *proactively* to a new updated manager node
  + Recording the operations so that when leadership is transferred, the new leader can continue this process correctly.

Some key issues:

### Order of Rolling Updates

We need to compute the correct ordering of the nodes before rolling update for certain types of groups...   for workers this is not essential but for managers this is critical in order to avoid scenario where the leader itself gets terminated.

At this moment, my idea is to have this computation be the responsibility of the Flavor plugin.  The group controller depends on the Flavor to determine health of a node, it probably make sense to add a new RPC method to have the Flavor determine the proper ordering of rolling update.   If necessary, the Flavor can also determine the mapping of a physical node to a swarm node (for example).  This requires addition of a new RPC method.

Note that the group controller does compute a 'Plan' and we can have this ordering of updates be the detail part of the plan.   This plan is then persisted in the backend (e.g. Swarm raft/ etcd) as described next:

### Status of Rolling Update

We need a way to record the transactions as we perform the rolling update.  This is important for #782 and necessary for continuation of the update when a new leader takes over the coordination of the updates.

As I described in the comment for #782, I am wondering if we can leverage the metadata plugin (the vars plugin).   When the manager gets a user's commit and detects a rolling update is required, it can launch an instance of the vars plugin and call it `updating`.  This will create a new key in the swarm raft (or whatever backend -- be it etcd or file) to store data but the plugin instance is running in the same process as the rest of infrakit.   The existence of the `updating` namespace via the plugin presence will inform other plugins that an update is in progress.   We can then write the instances / transactions / progress into the backend store (schema TBD) and this data can be queried by all of the other plugins (in process or out).  When the leadership is transferred, the new leader can continue based on this state.  The user can also query the state via the CLI.  When the update completes, the plugin instance stops and can archive this data and remove the `updating` namespace.  The update is considered complete when all the "Plan" steps described in the previous section are completed.

### Pacing of Updates
Similar to the discussion in #782 -- we can gate the calls to Destroy and Provision of the new nodes and continuation to the next target of update with checks against the health of the node (via Flavor) and against the stored status/ plan described above.

### Leader Transfer and Handling Failure During Updates
It's pretty tricky in the self-updating scenario because if we store the state / plan for the update in the same swarm raft and somehow the quorum is lost, we may not be able to read that data back out.  But having a copy somewhere (locally on disk of the running leader or say S3) isn't ideal either.  I think initially I'd still go with storing the information in the Swarm raft to keep things simple.  I'd make sure the ordering and leadership transfers are taking place properly, so that at any given time, the quorum is always up and running.  In the event that a new replacement manager node fails to come up, the update will have to come to a halt and wait for human intervention.

There's also the case where a network interruption or slowness of the running leader causing the leadership to change.  So now the ordering described above is no longer valid -- the next node to be terminated and replaced maybe the leader now.  So we'd have to build in a way for the group controller to *never* terminate itself (suicide).   I am thinking this mechanism could even do away the need to even compute the ordering of rolling update altogether...   We should explore that a bit... maybe it's not so much the ordering that matters but the specific identities of the nodes whose rolling updates need to be tightly coordinated / single-threaded would be sufficient.

Anyway sorry for the braindump.  I will think about this some more and let me know your thoughts.  I think the vars plugin solution has some legs and could be the first place to start...

**Comment by kaufers** [comment]
@chungers Thanks for the detailed info; I like the design.

I would like to talk more about the pre-defined ordering. Since, as you stated, leadership may change during an update, could we instead track the nodes that have and have not been updated? Then, when picking the next node to update, we'd never pick the current leader and, if that's the last one left, we'd force leadership change. Then, when the new leader wakes up, it would get the persisted state and continue the algorithm; in this case, the only manager left would no longer be the current leader and the update could be applied.

**Comment by chungers** [comment]
I think we can assume that the node that is running the code is always the leader... so the requirement to compute ordering may be reduced to something as simple as "thou shall not terminate self".   So when the leader is terminating nodes, it first checks that if the target isn't itself.  If it is, then it just picks one from a list of nodes that have yet to receive an update.  Since we will be writing the progress of the rolling updates into raft, we'd know which nodes have completed, and by extension, which nodes need to receive update.  The leader just needs to pick one.  If there are none, then the update is complete.  Example:

1. Managers A, B, C, D, E need to be rolling updated.  A is currently the leader.
2. There are no records in raft about which node has been updated.  So A picks from the list of [A, B, C, D, E] to update. 
3. A happens to pick A from this list.
4. A determines that A is itself.  So it can't destroy itself.  A picks another node.  A picks B.
5. B is updated.  B is now written into raft.
6. A continues this for C, D, and E.
7. A now can force a leadership change, say to B.  <=== A may not even have to do this here?
8. B now is the leader.  It reads from raft and sees that only A has not been updated.  It updates A.

**Comment by chungers** [comment]
I'm going to work on the very first step of making sure a leader doesn't destroy itself.  This may mean we would leave the leader without an update.  In a follow up I will work on handing over leader status to an updated node to continue the rolling update by finishing the last unupdated node.

**Comment by kaufers** [comment]
@chungers I want to ensure that we don't miss the "Pacing of Updates" in https://github.com/docker/infrakit/issues/783#issuecomment-348612516

Today (just verified) that a rolling update of the managers destroys all 3 (in the correct order now) and does not want for the replacements to join the swarm.

**Comment by kaufers** [comment]
This work is completed via:

https://github.com/docker/infrakit/pull/869
https://github.com/docker/infrakit/pull/864
https://github.com/docker/infrakit/pull/859
https://github.com/docker/infrakit/pull/856
https://github.com/docker/infrakit/pull/844
https://github.com/docker/infrakit/pull/841
