### ISSUE TITLE
Add optional health check path to LB route

### ISSUE THREAD

**Issue by ericvn** [docker/infrakit#794]
This issue is to discuss the design for adding a health check URL to the LB Route structure. It would be processed optionally by the LBs.

The IBM Cloud LB has a health check that is added whenever a Route is published. The check varies by the route protocol:

 - HTTP: An HTTP GET request against a pre-specified URL is sent to the back-end server port. The server port is marked healthy upon receiving a 200 OK response. The default GET URL is “/” via the GUI, and it can be customized.

- TCP: The Load Balancer attempts to open a TCP connection with the back-end server on a specified TCP port. The server port is marked healthy if the connection attempt is successful, and the connection is then closed.

    - Expecting ‘/’ to return a 200 means by default means that people either need to have their nodes do this or they must update the health check route specifically for their node.

For the publishing of a common TCP route this is OK. The service will react to the TCP connection and the node shows as healthy and requests are processed normally.

The issue happens when the route contains an HTTP protocol, as happens for SSL termination. In this case the LB is now trying a GET against the default "/" expecting a 200 response. If a 200 isn't returned, the node is marked unhealthy. This could cause all nodes to be marked unhealthy and then any requests coming into the LB will fail with a 503 Unavailable response.

One proposal is to use a label on the `docker service create` to specify a health check path similar to the way a certificate is specified. It would be of the form path@port[,port]. InfraKit would process the label similar to the certificate label and add the path to the Route struct.

The IBM Cloud LB (and others if needed) would then use this to set the path of the health monitor associated with the Route.

Pros:
 - Doesn't require a change to the IBM Cloud LB.

Cons:
 - Not sure how many other LBs would find this useful.
 - Requires a user using a IBM Cloud LB to specify and maintain a route for health checks (could be their application path but it that changes..).

**Comment by chungers** [comment]
The design of using labels to indicate path is sound, but there are other issues:

A node in a swarm cluster can run containers of multiple services.  If service A isn't responding at the given path but service B on the same node publishing on a different port is ok, the LB will still mark the node as unhealthy, right?  So potentially one service can cause another to be unavailable simply by not responding during health check. 

Also because of IPVS a node that isn't responding to healthcheck really isn't guaranteed to be the node running the task.  The scheduler could move the task to a different node and yet IPVS can still route traffic to the task container.  

So given these two considerations, the way we think about healthcheck is split into healthcheck on the swarm service (which I think is a swarm feature) and healthcheck on the Docker engine itself at the ingress level.   So ideally a check by the LB on TCP on the nodes Docker port would suffice.  For example he AWS LB is a L4 LB so the protocol supported is TCP and you can set the protocol independently from the listener protocol.

**Comment by ericvn** [comment]
Talked with the IBM Cloud LB team about two options:
 1) Have a single health monitor that we could hook to the Docker engine using TCP (similar to AWS)
 2) Allow a health check path of "" which cause the LB to go back to TCP against that port.

At this time, they can't commit to doing either option in the time required.

So we will start working on a PR for the above design.

**Comment by chungers** [comment]
Closed by #796
